# Generated by Django 5.2.3 on 2025-07-01 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_complaintimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComplaintImage',
        ),
    ]
